# -*- coding: utf-8 -*-
"""Exercicios_modulo4_isys.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PvUeZPIVP0ja72jrJlOI1douAJibNN7B
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile carros.csv
# id,valor_venda,valor_manutencao,portas,pessoas,porta_malas
# 1,vhigh,med,2,2,small
# 2,med,vhigh,2,2,small
# 3,low,vhigh,2,2,small
# 4,low,high,2,2,small
# 5,low,high,2,2,small
# 6,low,high,4,4,big
# 7,low,high,4,4,big
# 8,low,med,2,2,small
# 9,low,med,2,2,small
# 10,low,med,2,2,small
# 11,low,med,4,4,big
# 12,low,low,2,2,small
# 13,low,low,4,4,small
# 14,low,low,4,4,med

# Commented out IPython magic to ensure Python compatibility.
# %%writefile musica.txt
# Roda Viva
# Chico Buarque
# 
# Tem dias que a gente se sente
# Como quem partiu ou morreu
# A gente estancou de repente
# Ou foi o mundo então que cresceu
# A gente quer ter voz ativa
# No nosso destino mandar
# Mas eis que chega a roda viva
# E carrega o destino pra lá
# 
# Roda mundo, roda-gigante
# Roda moinho, roda pião
# 
# O tempo rodou num instante
# Nas voltas do meu coração
# A gente vai contra a corrente
# Até não poder resistir
# Na volta do barco é que sente
# O quanto deixou de cumprir
# Faz tempo que a gente cultiva
# A mais linda roseira que há
# Mas eis que chega a roda viva
# E carrega a roseira pra lá
# 
# Roda mundo, roda-gigante
# Roda moinho, roda pião

"""**1.1. Extraia os valores valor_venda e armazena em uma lista.**"""

valor_venda = []
with open(file='./carros.csv', mode='r', encoding='utf8') as arquivo:
  linha=arquivo.readline() # lê o cabeçalho
  linha=arquivo.readline() # lê a primeira linha
  while linha:
    linha_sep = linha.split(sep=',') # quebra a string nas virgulas e salva os resultados em uma lista
    indice = linha_sep[2] # seleciona o segundo elemento da lista
    valor_venda.append(indice) # salva o valor na lista de valor_venda
    linha = arquivo.readline() # lê uma nova linha, se a linha não existir, salva o valor None

print(valor_venda)

"""1.2 Complete a função abaixo para extrair uma coluna, do arquivo csv em uma lista."""

def extrai_coluna_csv(nome_arquivo: str, indice_coluna: int, tipo_dado: str):

  coluna = []

  with open(file=nome_arquivo, mode='r', encoding='utf8') as na:
    line=na.readline()
    line=na.readline()
    while line:
      line_sep = line.split(sep=',')
      indice = line_sep[indice_coluna]
      if tipo_dado == 'str':
        str(indice)
      elif tipo_dado == 'int':
        int(indice)
      elif tipo_dado =='float':
        float(indice)
      else:
        bool(indice)

      coluna.append(indice)
      line = na.readline()
  
    
  return coluna

valor_manutencao = extrai_coluna_csv(nome_arquivo='./carros.csv', indice_coluna=2, tipo_dado='str')
print(valor_manutencao) # deve retornar ['med', 'vhigh', 'vhigh', ...]

porta_malas = extrai_coluna_csv(nome_arquivo='./carros.csv', indice_coluna=5, tipo_dado='str')
print(porta_malas) # deve retornar ['small', 'small', 'small', ...]