# -*- coding: utf-8 -*-
"""exercicio_modulo8_isys.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UKOB_VLsgB1DQEwM_7uAZdealakoRRyN

1)
"""

credito={'123':750,'456':812,'789':980}

for chave, valor in credito.items():
  print(f'Para o documento {chave}, o valor do score de crédito é {valor}.')

"""Correção: Neste caso o código já rodava sem erros."""

def pi()-->float:
  return 3.14159265359

"""Correção: Há um erro de sintaxe na definição de pi, onde a seta que representa o tipo de dado está escrita com dois traços. Abaixo a versão corrigida com a seta escrita de maneira apropriada (->)"""

def pi()->float:
  return 3.14159265359

pi=pi()
print(pi)