# -*- coding: utf-8 -*-
"""exercicio_modeulo5_isys.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IQ1t9Tmtt8mnzuwhnl4IOHvO-zx8nh2T
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile credito.csv
# id_vendedor,valor_emprestimos,quantidade_emprestimos,data
# 104271,448.0,1,20161208
# 21476,826.7,3,20161208
# 87440,313.6,3,20161208
# 15980,-8008.0,6,20161208
# 215906,2212.0,5,20161208
# 33696,2771.3,2,20161208
# 33893,2240.0,3,20161208
# 214946,-4151.0,18,20161208
# 123974,2021.95,2,20161208
# 225870,4039.0,2,20161208

emprestimos = []
with open(file='./credito.csv', mode='r', encoding='utf8') as fp:
  fp.readline() # cabeçalho
  linha = fp.readline()
  while linha:
    linha_emprestimo = {}
    linha_elementos = linha.strip().split(sep=',')
    linha_emprestimo['id_vendedor'] = linha_elementos[0]
    linha_emprestimo['valor_emprestimos'] = linha_elementos[1]
    linha_emprestimo['quantidade_emprestimos'] = linha_elementos[2]
    linha_emprestimo['data'] = linha_elementos[3]
    emprestimos.append(linha_emprestimo)
    linha = fp.readline()

for emprestimo in emprestimos:
  print(emprestimo)

"""1) Aplique a função map na lista de `emprestimos` para extrair os valores da chave `valor_emprestimos` na lista `valor_emprestimos_lista`. Faça também a conversão de `str` para `float`."""

valor_emprestimos_lista_map = map(lambda valor_emprestimo : float(valor_emprestimo['valor_emprestimos']), emprestimos)

valor_emprestimos_lista=list(valor_emprestimos_lista_map)
print(list(valor_emprestimos_lista))

"""2) Aplique a função filter na lista de `valor_emprestimos_lista` para filtrar apenas os valores maiores que zero (os valores negativas são erros na base de dados). Salve os valores na lista `valor_emprestimos_lista_filtrada`."""

valor_emprestimo_lista_filter = filter(lambda valor_filtro: valor_filtro > 0 , valor_emprestimos_lista)

valor_emprestimo_lista_filtrada=list(valor_emprestimo_lista_filter)
print(valor_emprestimo_lista_filtrada)

"""3) Aplique a função reduce para somar os elementos da lista `valor_emprestimos_lista_filtrada` na variavel `soma_valor_emprestimos`."""

from functools import reduce
soma_valor_emprestimos=reduce(lambda x, y:x+y, valor_emprestimo_lista_filtrada)
print(soma_valor_emprestimos)

"""4) Aplique a função reduce para extrair a média aritimética (mais informações [aqui](https://pt.wikipedia.org/wiki/M%C3%A9dia#M%C3%A9dia_aritm%C3%A9tica)) dos elementos da lista `valor_emprestimos_lista_filtrada` na variavel `media_valor_emprestimos`.

Dica: Para calcular o tamanho da lista, isto é a quantidade de elementos, utilize a função len(), dentro do argumento da função coloque a lista `valor_emprestimos_lista_filtrada`.
"""

from functools import reduce

media_valor_emprestimos = reduce(lambda x,y:x+y, valor_emprestimo_lista_filtrada)/len(valor_emprestimo_lista_filtrada)

print(media_valor_emprestimos)