# -*- coding: utf-8 -*-
"""Exercicio_modulo2_isys.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FeHbxvDEZl9JokozHxODTMebZp6_2TK4

# **Exercício *Listas***
"""

filmes = ["Um Sonho de Liberdade", "O Poderoso Chefão", "O Poderoso Chefão 2", "Batman: O Cavaleiro das Trevas", "12 Homens e uma Sentença", "A Lista de Schindler", "O Senhor dos Aneis: O Retorno do Rei", "Pulp Fiction: Tempo de Violência", "Três Homens em Conflito", "O Senhor dos Aneis: A Sociedade do Anel"]

print(filmes)

filmes_dois = filmes.pop(1)
print(filmes_dois)

print(filmes)

filmes.insert(0, "O Poderoso Chefão")

print(filmes)

"""# **Exercício *Conjuntos***"""

filmes.append("Pulp Fiction: Tempo de Violência")

filmes.append("Três Homens em Conflito")

filmes.append("O Senhor dos Aneis: A Sociedade do Anel")

print(filmes)

print(type(filmes))

print(set(filmes))

"""# **Exercício *Dicionários***"""

filmes = {
    1:{
       "Título": "Um Sonho de Liberdade",
       "Ano": 1994,
       "Sinopse": "Andy Dufresne é condenado a duas prisões perpétuas consecutivas pelas mortes de sua esposa e sua amante. Porém, só Andy sabe que ele não cometeu os crimes. No presídio, durante dezenove anos, ele faz amizade com Red, sofre as brutalidades da vida na cadeia, se adapta, ajuda os carcereiros, etc.",
      },
    2:{
       "Título": "O Poderoso Chefão",
       "Ano": 1972,
       "Sinopse": "Uma família mafiosa luta para estabelecer sua supremacia nos EUA depois da segunda guerra mundial. Uma tentativa de assassinato deixa o chefão Vito Corleone incapacitado e força os filhos Michael e Sonny a assumir os negócios."
      },
    3:{
       "Título": "O Poderoso Chefão 2",
       "Ano": 1974,
       "Sinopse": "Depois da máfia matar sua família, o jovem Vito foge da sua cidade na Sicília e vai para os EUA. Lá, ele assassina Black Hand Fanucci, que exigia dos comerciantes uma parte de seus ganhos. Com a morte de Fanucci, o poder de Vito cresce, mas sua família é o que mais importa para ele. Morando agora no Lago Tahoe, Michael planeja fazer incursões em Las Vegas e Havana com negócios ligados ao lazer, mas descobre que aliados como Hyman Roth estão tentando matá-lo."
      },
    4:{
       "Título": "Batman: O Cavaleiro das Trevas",
       "Ano": 2008,
       "Sinopse": "Após dois anos desde o surgimento do Batman (Christian Bale), os criminosos de Gotham City têm muito o que temer. Com a ajuda do tenente James Gordon (Gary Oldman) e do promotor público Harvey Dent (Aaron Eckhart), Batman luta contra o crime organizado. Acuados com o combate, os chefes do crime aceitam a proposta feita pelo Coringa (Heath Ledger) e o contratam para combater o Homem-Morcego."
      },
    5:{
       "Título": "12 Homens e uma Sentença",
       "Ano": 1957,
       "Sinopse": "Seguindo o encerramento do caso do julgamento do assassinato cometido por um adolescente, os membros do júri devem chegar a um consenso sobre qual será o veredito. Enquanto os 12 indivíduos estão fechados em uma sala para tomar uma decisão, onze deles votam pela condenação do réu, porém um deles acredita na inocência do jovem e tenta convencer os outros a mudarem seus votos, dando início a um conflito que ameaça inviabilizar o delicado processo que vai decidir o destino do acusado."
      },
    6:{
       "Título": "A Lista de Schindler",
       "Ano": 1993,
       "Sinopse": "O alemão Oskar Schindler viu na mão de obra judia uma solução barata e viável para lucrar com negócios durante a guerra. Com sua forte influência dentro do partido nazista, foi fácil conseguir as autorizações e abrir uma fábrica. O que poderia parecer uma atitude de um homem não muito bondoso, transformou-se em um dos maiores casos de amor à vida da História, pois este alemão abdicou de toda sua fortuna para salvar a vida de mais de mil judeus em plena luta contra o extermínio alemão."
      },
    7:{
       "Título": "O Senhor dos Aneis: O Retorno do Rei",
       "Ano": 2003,
       "Sinopse": "O confronto final entre as forças do bem e do mal que lutam pelo controle do futuro da Terra Média se aproxima. Sauron planeja um grande ataque a Minas Tirith, capital de Gondor, o que faz com que Gandalf e Pippin partam para o local na intenção de ajudar a resistência. Um exército é reunido por Theoden em Rohan, em mais uma tentativa de deter as forças de Sauron. Enquanto isso, Frodo, Sam e Gollum seguem sua viagem rumo à Montanha da Perdição para destruir o anel."
      },
    8:{
       "Título": "Pulp Fiction: Tempo de Violência",
       "Ano": 1994,
       "Sinopse": "Assassino que trabalha para a máfia se apaixona pela esposa de seu chefe quando é convidado a acompanhá-la, um boxeador descumpre sua promessa de perder uma luta e um casal tenta um assalto que rapidamente sai do controle."
      },
    9:{
       "Título": "Três Homens em Conflito",
       "Ano": 1966,
       "Sinopse": "Durante a Guerra Civil Americana, um pistoleiro misterioso e dois estrangeiros decidem juntar suas forças para encontrar um tesouro escondido. Cada um dos homens conhece apenas uma parte da localização da fortuna, o que força essa parceria. O problema é que nenhum deles tem a intenção de dividir a riqueza."
      },
    10:{
        "Título": "O Senhor dos Aneis: A Sociedade do Anel",
        "Ano": 2001,
        "Sinopse": "Em uma terra fantástica e única, um hobbit recebe de presente de seu tio um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso, o hobbit Frodo tem um caminho árduo pela frente, onde encontra perigo, medo e seres bizarros. Ao seu lado para o cumprimento desta jornada, ele aos poucos pode contar com outros hobbits, um elfo, um anão, dois humanos e um mago, totalizando nove seres que formam a Sociedade do Anel."
       }
    }

print(filmes)