# -*- coding: utf-8 -*-
"""exercicios_modulo6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yaFr0DT8tPmdQdOV-NxMRHJ1_BK9dA2b

##Exercícios módulo 6
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile carros.csv
# id,valor_venda,valor_manutencao,portas,pessoas,porta_malas
# 1,vhigh,med,2,2,small
# 2,med,vhigh,2,2,small
# 3,low,vhigh,2,2,small
# 4,low,high,2,2,small
# 5,low,high,2,2,small
# 6,low,high,4,4,big
# 7,low,high,4,4,big
# 8,low,med,2,2,small
# 9,low,med,2,2,small
# 10,low,med,2,2,small
# 11,low,med,4,4,big
# 12,low,low,2,2,small
# 13,low,low,4,4,small
# 14,low,low,4,4,med

# Commented out IPython magic to ensure Python compatibility.
# %%writefile musica.txt
# Roda Viva
# Chico Buarque
# 
# Tem dias que a gente se sente
# Como quem partiu ou morreu
# A gente estancou de repente
# Ou foi o mundo então que cresceu
# A gente quer ter voz ativa
# No nosso destino mandar
# Mas eis que chega a roda viva
# E carrega o destino pra lá
# Roda mundo, roda-gigante
# Roda moinho, roda pião
# O tempo rodou num instante
# Nas voltas do meu coração
# A gente vai contra a corrente
# Até não poder resistir
# Na volta do barco é que sente
# O quanto deixou de cumprir
# Faz tempo que a gente cultiva
# A mais linda roseira que há
# Mas eis que chega a roda viva
# E carrega a roseira pra lá
# Roda mundo, roda-gigante
# Roda moinho, roda pião

"""1) Arquivo txt"""

class ArquivoTexto(object):

  def __init__(self, arquivo:str):
    self.arquivo=arquivo
    self.conteudo=self._extrair_conteudo()
    #self.colunas=self._extrair_nome_colunas()

  def _extrair_conteudo(self):
    conteudo=None
    with open(file=self.arquivo, mode='r', encoding='utf8') as arquivo:
      conteudo=arquivo.readlines()
    return conteudo

  def extrair_linha(self, numero_linha:int):
    return self.conteudo[numero_linha-1]

arquivo_texto=ArquivoTexto(arquivo='musica.txt')

numero_linha=1
print(arquivo_texto.extrair_linha(numero_linha=numero_linha))

numero_linha=10
print(arquivo_texto.extrair_linha(numero_linha=numero_linha))

"""2) Arquivo txt"""

class ArquivoCSV(ArquivoTexto):

  def __init__(self, arquivo:str):
    super().__init__(arquivo=arquivo)
    self.colunas=self._extrair_nome_colunas()

  def _extrair_nome_colunas(self):
    return self.conteudo[0].strip().split(sep=',')

  def extrair_coluna(self, indice_coluna:str):
    coluna=list()
    for linha in self.conteudo:
      conteudo_linha=linha.strip().split(sep=',')
      coluna.append(conteudo_linha[indice_coluna])
    coluna.pop(0)
    return coluna

arquivo_csv=ArquivoCSV(arquivo='carros.csv')

numero_linha=1
print(arquivo_csv.extrair_linha(numero_linha=numero_linha))

print(arquivo_csv.colunas)

numero_linha=10
print(arquivo_csv.extrair_linha(numero_linha=numero_linha))

indice_coluna=2
print(arquivo_csv.extrair_coluna(indice_coluna=indice_coluna))